import type { Wrestler } from "@workspace/api-client-react";
import { WrestlerBrand, WrestlerAlignment } from "@workspace/api-client-react";

const R = WrestlerBrand.RAW;
const SD = WrestlerBrand.SMACKDOWN;
const NXT = WrestlerBrand.NXT;
const FA = WrestlerBrand.FREE_AGENT;
const FACE = WrestlerAlignment.FACE;
const HEEL = WrestlerAlignment.HEEL;
const TWEENER = WrestlerAlignment.TWEENER;

export function slugifyName(name: string): string {
  return name
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function seedWrestlerId(name: string): string {
  return `wrestler-${slugifyName(name)}`;
}

const RAW_SEED: Omit<Wrestler, "id">[] = [
  // ── MEN ──────────────────────────────────────────────────────────────────
  { name: "Abyss",                          brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/abyss.png" },
  { name: "Adam Pearce",                    brand: R,    alignment: HEEL, imageUrl: "/wrestlers/adam-pearce.webp" },
  { name: "Afa",                            brand: FA,   alignment: FACE, imageUrl: "/wrestlers/afa.png" },
  { name: "AJ Styles",                      brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/aj-styles.png" },
  { name: "Akira Tozawa",                   brand: R,    alignment: FACE, imageUrl: "/wrestlers/akira-tozawa.png" },
  { name: "Aleister Black",                 brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/aleister-black.png" },
  { name: "Alex Shelley",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/alex-shelley.png" },
  { name: "Andre Chase",                    brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/andre-chase.png" },
  { name: "Andre The Giant",                brand: FA,   alignment: FACE, imageUrl: "/wrestlers/andre-the-giant.png" },
  { name: "Angel",                          brand: SD,   alignment: FACE, imageUrl: "/wrestlers/angel.png" },
  { name: "Angelo Dawkins",                 brand: R,    alignment: FACE, imageUrl: "/wrestlers/angelo-dawkins.png" },
  { name: "Apollo Crews",                   brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/apollo-crews.png" },
  { name: "Austin Theory",                  brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/austin-theory.png" },
  { name: "Axiom",                          brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/axiom.png" },
  { name: "Batista",                        brand: FA,   alignment: FACE, imageUrl: "/wrestlers/batista.png" },
  { name: "Berto",                          brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/berto.png" },
  { name: "Big E",                          brand: FA,   alignment: FACE, imageUrl: "/wrestlers/big-e.png" },
  { name: "Big Poppa Pump",                 brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/big-poppa-pump.png" },
  { name: "Billy Graham",                   brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/billy-graham.png" },
  { name: "Billy Gunn",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/billy-gunn.png" },
  { name: "Boogeyman",                      brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/boogeyman.png" },
  { name: "Booker T",                       brand: FA,   alignment: FACE, imageUrl: "/wrestlers/booker-t.png" },
  { name: "Bray Wyatt",                     brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/bray-wyatt.png" },
  { name: "Bret Hart",                      brand: FA,   alignment: FACE, imageUrl: "/wrestlers/bret-hart.png" },
  { name: "British Bulldog",                brand: FA,   alignment: FACE, imageUrl: "/wrestlers/british-bulldog.png" },
  { name: "Brock Lesnar",                   brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/brock-lesnar.png" },
  { name: "Bron Breakker",                  brand: R,    alignment: HEEL, imageUrl: "/wrestlers/bron-breakker.png" },
  { name: "Bronson Reed",                   brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/bronson-reed.png" },
  { name: "Brooks Jensen",                  brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/brooks-jensen.png" },
  { name: "Brutus Creed",                   brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/brutus-creed.png" },
  { name: "Bubba Ray Dudley",               brand: FA,   alignment: FACE, imageUrl: "/wrestlers/bubba-ray-dudley.png" },
  { name: "Cactus Jack",                    brand: FA,   alignment: FACE, imageUrl: "/wrestlers/cactus-jack.png" },
  { name: "Carmelo Hayes",                  brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/carmelo-hayes.png" },
  { name: "Chad Gable",                     brand: R,    alignment: HEEL, imageUrl: "/wrestlers/chad-gable.png" },
  { name: "Channing Lorenzo",               brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/channing-lorenzo.png" },
  { name: "Charlie Dempsey",                brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/charlie-dempsey.png" },
  { name: "Chris Sabin",                    brand: FA,   alignment: FACE, imageUrl: "/wrestlers/chris-sabin.png" },
  { name: "CM Punk",                        brand: R,    alignment: FACE, imageUrl: "/wrestlers/cm-punk.png" },
  { name: "American Nightmare Cody Rhodes", brand: SD,   alignment: FACE, notes: "Undisputed WWE Champion", imageUrl: "/wrestlers/american-nightmare-cody-rhodes.png" },
  { name: "Cruz Del Toro",                  brand: SD,   alignment: FACE, imageUrl: "/wrestlers/cruz-del-toro.png" },
  { name: "D-Von Dudley",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/d-von-dudley.png" },
  { name: "D'Lo Brown",                     brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/dlo-brown.png" },
  { name: "Damian Priest",                  brand: SD,   alignment: TWEENER, imageUrl: "/wrestlers/damian-priest.png" },
  { name: "Demon Finn Balor",               brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/demon-finn-balor.png" },
  { name: "Dexter Lumis",                   brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/dexter-lumis.png" },
  { name: "Diamond Dallas Page",            brand: FA,   alignment: FACE, imageUrl: "/wrestlers/diamond-dallas-page.png" },
  { name: "Diesel",                         brand: FA,   alignment: FACE, imageUrl: "/wrestlers/diesel.png" },
  { name: "Doink The Clown",                brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/doink-the-clown.png" },
  { name: "Dominik Mysterio",               brand: R,    alignment: HEEL, imageUrl: "/wrestlers/dominik-mysterio.png" },
  { name: "Dragon Lee",                     brand: SD,   alignment: FACE, imageUrl: "/wrestlers/dragon-lee.png" },
  { name: "Drew McIntyre",                  brand: R,    alignment: HEEL, imageUrl: "/wrestlers/drew-mcintyre.png" },
  { name: "Dude Love",                      brand: FA,   alignment: FACE, imageUrl: "/wrestlers/dude-love.png" },
  { name: "Dusty Rhodes",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/dusty-rhodes.png" },
  { name: "Eddie Guerrero",                 brand: FA,   alignment: FACE, imageUrl: "/wrestlers/eddie-guerrero.png" },
  { name: "El Grande Americano",            brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/el-grande-americano.png" },
  { name: "El Hijo del Vikingo",            brand: FA,   alignment: FACE, imageUrl: "/wrestlers/el-hijo-del-vikingo.png" },
  { name: "Elton Prince",                   brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/elton-prince.png" },
  { name: "Eric Bischoff",                  brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/eric-bischoff.png" },
  { name: "Erick Rowan",                    brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/erick-rowan.png" },
  { name: "Erik",                           brand: FA,   alignment: FACE, imageUrl: "/wrestlers/erik.png" },
  { name: "Ethan Page",                     brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/ethan-page.png" },
  { name: "Faarooq",                        brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/faarooq.png" },
  { name: "Finn Balor",                     brand: R,    alignment: HEEL, imageUrl: "/wrestlers/finn-balor.png" },
  { name: "Goldberg",                       brand: FA,   alignment: FACE, imageUrl: "/wrestlers/goldberg.png" },
  { name: "Grayson Waller",                 brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/grayson-waller.png" },
  { name: "Gunther",                        brand: R,    alignment: HEEL, notes: "Ring General", imageUrl: "/wrestlers/gunther.png" },
  { name: "Haku",                           brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/haku.png" },
  { name: "Hank Walker",                    brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/hank-walker.png" },
  { name: "Hollywood Hogan",                brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/hollywood-hogan.png" },
  { name: "Honky Tonk Man",                 brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/honky-tonk-man.png" },
  { name: "Hulk Hogan",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/hulk-hogan.png" },
  { name: "Hunter Hearst Helmsley",         brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/hunter-hearst-helmsley.png" },
  { name: "Ilja Dragunov",                  brand: FA,   alignment: FACE, imageUrl: "/wrestlers/ilja-dragunov.png" },
  { name: "Ivar",                           brand: FA,   alignment: FACE, imageUrl: "/wrestlers/ivar.png" },
  { name: "Jacob Fatu",                     brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/jacob-fatu.png" },
  { name: "Jamal",                          brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/jamal.png" },
  { name: "JBL",                            brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/jbl.png" },
  { name: "JC Mateo",                       brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/jc-mateo.png" },
  { name: "JD McDonagh",                    brand: R,    alignment: HEEL, imageUrl: "/wrestlers/jd-mcdonagh.png" },
  { name: "Je'Von Evans",                   brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/jevon-evans.png" },
  { name: "Jean Paul Levesque",             brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/jean-paul-levesque.png" },
  { name: "Jesse Ventura",                  brand: FA,   alignment: FACE, imageUrl: "/wrestlers/jesse-ventura.png" },
  { name: "Jey Uso",                        brand: R,    alignment: FACE, imageUrl: "/wrestlers/jey-uso.png" },
  { name: "Jim Neidhart",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/jim-neidhart.png" },
  { name: "Jimmy Uso",                      brand: SD,   alignment: TWEENER, imageUrl: "/wrestlers/jimmy-uso.png" },
  { name: "Joaquin Wilde",                  brand: SD,   alignment: FACE, imageUrl: "/wrestlers/joaquin-wilde.png" },
  { name: "Joe Gacy",                       brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/joe-gacy.png" },
  { name: "Joe Hendry",                     brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/joe-hendry.png" },
  { name: "John Cena",                      brand: FA,   alignment: FACE, imageUrl: "/wrestlers/john-cena.png" },
  { name: "Johnny Gargano",                 brand: FA,   alignment: FACE, imageUrl: "/wrestlers/johnny-gargano.png" },
  { name: "Josh Briggs",                    brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/josh-briggs.png" },
  { name: "Julius Creed",                   brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/julius-creed.png" },
  { name: "Junkyard Dog",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/junkyard-dog.png" },
  { name: "Kane",                           brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/kane.png" },
  { name: "Ken Shamrock",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/ken-shamrock.png" },
  { name: "Kevin Nash",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/kevin-nash.png" },
  { name: "Kevin Owens",                    brand: SD,   alignment: FACE, imageUrl: "/wrestlers/kevin-owens.png" },
  { name: "Kit Wilson",                     brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/kit-wilson.png" },
  { name: "Kofi Kingston",                  brand: FA,   alignment: FACE, imageUrl: "/wrestlers/kofi-kingston.png" },
  { name: "Kurt Angle",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/kurt-angle.png" },
  { name: "LA Knight",                      brand: SD,   alignment: FACE, imageUrl: "/wrestlers/la-knight.png" },
  { name: "Lex Luger",                      brand: FA,   alignment: FACE, imageUrl: "/wrestlers/lex-luger.png" },
  { name: "Lexis King",                     brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/lexis-king.png" },
  { name: "Logan Paul",                     brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/logan-paul.png" },
  { name: "Ludwig Kaiser",                  brand: R,    alignment: HEEL, imageUrl: "/wrestlers/ludwig-kaiser.png" },
  { name: "Mankind",                        brand: FA,   alignment: FACE, imageUrl: "/wrestlers/mankind.png" },
  { name: "Mark Henry",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/mark-henry.png" },
  { name: "Montez Ford",                    brand: R,    alignment: FACE, imageUrl: "/wrestlers/montez-ford.png" },
  { name: "Mosh",                           brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/mosh.png" },
  { name: "Mr. Iguana",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/mr-iguana.png" },
  { name: "Mr. Perfect",                    brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/mr-perfect.png" },
  { name: "Myles Borne",                    brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/myles-borne.png" },
  { name: "Nathan Frazer",                  brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/nathan-frazer.png" },
  { name: "New Jack",                       brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/new-jack.png" },
  { name: "Nick Aldis",                     brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/nick-aldis.png" },
  { name: "Noam Dar",                       brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/noam-dar.png" },
  { name: "Oba Femi",                       brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/oba-femi.png" },
  { name: "Omos",                           brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/omos.png" },
  { name: "Original El Grande Americano",   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/original-el-grande-americano.png" },
  { name: "Otis",                           brand: SD,   alignment: FACE, imageUrl: "/wrestlers/otis.png" },
  { name: "Pat McAfee",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/pat-mcafee.png" },
  { name: "Paul Orndorff",                  brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/paul-orndorff.png" },
  { name: "Penta",                          brand: FA,   alignment: FACE, imageUrl: "/wrestlers/penta.png" },
  { name: "Pete Dunne",                     brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/pete-dunne.png" },
  { name: "Psycho Clown",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/psycho-clown.png" },
  { name: "R-Truth",                        brand: R,    alignment: FACE, imageUrl: "/wrestlers/r-truth.png" },
  { name: "Randy Orton",                    brand: SD,   alignment: FACE, imageUrl: "/wrestlers/randy-orton.png" },
  { name: "Randy Savage",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/randy-savage.png" },
  { name: "Razor Ramon",                    brand: FA,   alignment: FACE, imageUrl: "/wrestlers/razor-ramon.png" },
  { name: "Rey Fenix",                      brand: FA,   alignment: FACE, imageUrl: "/wrestlers/rey-fenix.png" },
  { name: "Rey Mysterio",                   brand: SD,   alignment: FACE, imageUrl: "/wrestlers/rey-mysterio.png" },
  { name: "Rick Rude",                      brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/rick-rude.png" },
  { name: "Rick Steiner",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/rick-steiner.png" },
  { name: "Ricky Saints",                   brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/ricky-saints.png" },
  { name: "Ridge Holland",                  brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/ridge-holland.png" },
  { name: "Rikishi",                        brand: FA,   alignment: FACE, imageUrl: "/wrestlers/rikishi.png" },
  { name: "Road Dogg",                      brand: FA,   alignment: FACE, imageUrl: "/wrestlers/road-dogg.png" },
  { name: "Rob Van Dam",                    brand: FA,   alignment: FACE, imageUrl: "/wrestlers/rob-van-dam.png" },
  { name: "Rocky Maivia",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/rocky-maivia.png" },
  { name: "Roddy Piper",                    brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/roddy-piper.png" },
  { name: "Roman Reigns",                   brand: SD,   alignment: TWEENER, imageUrl: "/wrestlers/roman-reigns.png" },
  { name: "Rosey",                          brand: FA,   alignment: FACE, imageUrl: "/wrestlers/rosey.png" },
  { name: "Rusev",                          brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/rusev.png" },
  { name: "Sami Zayn",                      brand: R,    alignment: FACE, imageUrl: "/wrestlers/sami-zayn.png" },
  { name: "Sandman",                        brand: FA,   alignment: FACE, imageUrl: "/wrestlers/sandman.png" },
  { name: "Santos Escobar",                 brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/santos-escobar.png" },
  { name: "Scott Hall",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/scott-hall.png" },
  { name: "Scott Steiner",                  brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/scott-steiner.png" },
  { name: "Seth Rollins",                  brand: R,    alignment: FACE, imageUrl: "/wrestlers/seth-rollins.png" },
  { name: "Shawn Michaels",                 brand: FA,   alignment: FACE, imageUrl: "/wrestlers/shawn-michaels.png" },
  { name: "Shawn Spears",                   brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/shawn-spears.png" },
  { name: "Sheamus",                        brand: FA,   alignment: FACE, imageUrl: "/wrestlers/sheamus.png" },
  { name: "Shinsuke Nakamura",              brand: SD,   alignment: TWEENER, imageUrl: "/wrestlers/shinsuke-nakamura.png" },
  { name: "Sid Justice",                    brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/sid-justice.png" },
  { name: "Sika",                           brand: FA,   alignment: FACE, imageUrl: "/wrestlers/sika.png" },
  { name: "Solo Sikoa",                     brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/solo-sikoa.png" },
  { name: "Stone Cold Steve Austin",        brand: FA,   alignment: FACE, imageUrl: "/wrestlers/stone-cold-steve-austin.png" },
  { name: "Syxx",                           brand: FA,   alignment: FACE, imageUrl: "/wrestlers/syxx.png" },
  { name: "Talla Tonga",                    brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/talla-tonga.png" },
  { name: "Tama",                           brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/tama.png" },
  { name: "Tama Tonga",                     brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/tama-tonga.png" },
  { name: "Tank Ledger",                    brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/tank-ledger.png" },
  { name: "Tavion Heights",                 brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/tavion-heights.png" },
  { name: "Terry Funk",                     brand: FA,   alignment: FACE, imageUrl: "/wrestlers/terry-funk.png" },
  { name: "The Fiend",                      brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/the-fiend.png" },
  { name: "The Great Khali",                brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/the-great-khali.png" },
  { name: "The Great Muta",                 brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/the-great-muta.png" },
  { name: "The Hurricane",                  brand: FA,   alignment: FACE, imageUrl: "/wrestlers/the-hurricane.png" },
  { name: "The Iron Sheik",                 brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/the-iron-sheik.png" },
  { name: "The Miz",                        brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/the-miz.jpg" },
  { name: "The Rock",                       brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/the-rock.png" },
  { name: "Thrasher",                       brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/thrasher.png" },
  { name: "Tito Santana",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/tito-santana.png" },
  { name: "Tommaso Ciampa",                 brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/tommaso-ciampa.png" },
  { name: "Tonga Loa",                      brand: SD,   alignment: HEEL, imageUrl: "/wrestlers/tonga-loa.png" },
  { name: "Tony D'Angelo",                  brand: NXT,  alignment: HEEL, imageUrl: "/wrestlers/tony-dangelo.png" },
  { name: "Trick Williams",                 brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/trick-williams.png" },
  { name: "Triple H",                       brand: FA,   alignment: FACE, imageUrl: "/wrestlers/triple-h.png" },
  { name: "Tyler Bate",                     brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/tyler-bate.png" },
  { name: "Tyler Breeze",                   brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/tyler-breeze.png" },
  { name: "Ultimate Warrior",               brand: FA,   alignment: FACE, imageUrl: "/wrestlers/ultimate-warrior.png" },
  { name: "Umaga",                          brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/umaga.png" },
  { name: "Uncle Howdy",                    brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/uncle-howdy.png" },
  { name: "Undertaker",                     brand: FA,   alignment: TWEENER, imageUrl: "/wrestlers/undertaker.png" },
  { name: "Vader",                          brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/vader.png" },
  { name: "Wade Barrett",                   brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/wade-barrett.png" },
  { name: "William Regal",                  brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/william-regal.png" },
  { name: "X-Pac",                          brand: FA,   alignment: FACE, imageUrl: "/wrestlers/x-pac.png" },
  { name: "Xavier Woods",                   brand: FA,   alignment: FACE, imageUrl: "/wrestlers/xavier-woods.png" },
  { name: "Yokozuna",                       brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/yokozuna.png" },
  { name: "Yoshiki Inamura",                brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/yoshiki-inamura.png" },

  // ── WOMEN ─────────────────────────────────────────────────────────────────
  { name: "AJ Lee",                         brand: FA,   alignment: FACE },
  { name: "Alba Fyre",                      brand: NXT,  alignment: FACE },
  { name: "Alexa Bliss",                    brand: R,    alignment: TWEENER },
  { name: "Alundra Blayze",                 brand: FA,   alignment: FACE },
  { name: "Asuka",                          brand: R,    alignment: TWEENER },
  { name: "B-Fab",                          brand: NXT,  alignment: FACE },
  { name: "Bayley",                         brand: SD,   alignment: FACE },
  { name: "Becky Lynch",                    brand: R,    alignment: FACE },
  { name: "Bianca Belair",                  brand: SD,   alignment: FACE },
  { name: "Blake Monroe",                   brand: NXT,  alignment: FACE },
  { name: "Bull Nakano",                    brand: FA,   alignment: HEEL },
  { name: "Candice LeRae",                  brand: NXT,  alignment: FACE },
  { name: "Charlotte Flair",                brand: FA,   alignment: FACE },
  { name: "Chelsea Green",                  brand: SD,   alignment: HEEL },
  { name: "Chyna",                          brand: FA,   alignment: FACE },
  { name: "Eve Torres",                     brand: FA,   alignment: FACE },
  { name: "Fallon Henley",                  brand: NXT,  alignment: FACE },
  { name: "Flammer",                        brand: FA,   alignment: FACE },
  { name: "Giulia",                         brand: NXT,  alignment: FACE },
  { name: "Ivy Nile",                       brand: NXT,  alignment: FACE },
  { name: "Iyo Sky",                        brand: R,    alignment: HEEL },
  { name: "Izzi Dame",                      brand: NXT,  alignment: HEEL },
  { name: "Jacy Jayne",                     brand: NXT,  alignment: HEEL },
  { name: "Jade Cargill",                   brand: SD,   alignment: FACE },
  { name: "Jaida Parker",                   brand: NXT,  alignment: HEEL },
  { name: "Jazmyn Nyx",                     brand: NXT,  alignment: HEEL },
  { name: "Jordynne Grace",                 brand: FA,   alignment: FACE },
  { name: "Kairi Sane",                     brand: R,    alignment: HEEL },
  { name: "Karmen Petrovic",                brand: NXT,  alignment: FACE },
  { name: "Kelani Jordan",                  brand: NXT,  alignment: FACE },
  { name: "Kiana James",                    brand: NXT,  alignment: HEEL },
  { name: "Lash Legend",                    brand: NXT,  alignment: HEEL },
  { name: "Lita",                           brand: FA,   alignment: FACE },
  { name: "Liv Morgan",                     brand: R,    alignment: HEEL },
  { name: "Lola Vice",                      brand: NXT,  alignment: HEEL },
  { name: "Lyra Valkyria",                  brand: R,    alignment: FACE },
  { name: "Maryse",                         brand: FA,   alignment: HEEL },
  { name: "Maxxine Dupri",                  brand: SD,   alignment: FACE },
  { name: "Michelle McCool",                brand: FA,   alignment: FACE },
  { name: "Michin",                         brand: NXT,  alignment: FACE },
  { name: "Molly Holly",                    brand: FA,   alignment: FACE },
  { name: "Naomi",                          brand: SD,   alignment: FACE },
  { name: "Natalya",                        brand: FA,   alignment: FACE },
  { name: "Nia Jax",                        brand: R,    alignment: HEEL },
  { name: "Nikki Bella",                    brand: FA,   alignment: FACE },
  { name: "Nikki Cross",                    brand: FA,   alignment: TWEENER },
  { name: "Nikkita Lyons",                  brand: NXT,  alignment: FACE },
  { name: "Piper Niven",                    brand: SD,   alignment: HEEL },
  { name: "Raquel Rodriguez",               brand: SD,   alignment: FACE },
  { name: "Rhea Ripley",                    brand: R,    alignment: FACE },
  { name: "Roxanne Perez",                  brand: NXT,  alignment: HEEL },
  { name: "Sensational Sherri",             brand: FA,   alignment: HEEL },
  { name: "Sol Ruca",                       brand: NXT,  alignment: FACE },
  { name: "Stacy Keibler",                  brand: FA,   alignment: FACE },
  { name: "Stephanie McMahon",              brand: FA,   alignment: FACE },
  { name: "Stephanie Vaquer",               brand: NXT,  alignment: FACE },
  { name: "Tatum Paxley",                   brand: NXT,  alignment: HEEL },
  { name: "Thea Hail",                      brand: NXT,  alignment: FACE },
  { name: "Tiffany Stratton",               brand: SD,   alignment: HEEL },
  { name: "Trish Stratus",                  brand: FA,   alignment: FACE },
  { name: "Victoria",                       brand: FA,   alignment: HEEL, imageUrl: "/wrestlers/victoria.png" },
  { name: "Wendy Choo",                     brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/wendy-choo.png" },
  { name: "Wren Sinclair",                  brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/wren-sinclair.png" },
  { name: "Zaria",                          brand: NXT,  alignment: FACE, imageUrl: "/wrestlers/zaria.png" },
  { name: "Zelina Vega",                    brand: SD,   alignment: FACE, imageUrl: "/wrestlers/zelina-vega.png" },
  { name: "Zoey Stark",                     brand: R,    alignment: HEEL, imageUrl: "/wrestlers/zoey-stark.png" },
];

export const SEED_ROSTER: Wrestler[] = RAW_SEED.map((w) => ({
  id: seedWrestlerId(w.name),
  ...w,
}));

/**
 * Lookup set of known women's-division names. Used by the roster M/F filter
 * to classify the seed roster without needing a `gender` field on Wrestler.
 * Custom (user-added) wrestlers default to "M" unless their name is here.
 */
export const WOMEN_NAMES: ReadonlySet<string> = new Set([
  "AJ Lee", "Alba Fyre", "Alexa Bliss", "Alundra Blayze", "Asuka", "B-Fab",
  "Bayley", "Becky Lynch", "Bianca Belair", "Blake Monroe", "Bull Nakano",
  "Candice LeRae", "Charlotte Flair", "Chelsea Green", "Chyna", "Eve Torres",
  "Fallon Henley", "Flammer", "Giulia", "Ivy Nile", "Iyo Sky", "Izzi Dame",
  "Jacy Jayne", "Jade Cargill", "Jaida Parker", "Jazmyn Nyx", "Jordynne Grace",
  "Kairi Sane", "Karmen Petrovic", "Kelani Jordan", "Kiana James", "Lash Legend",
  "Lita", "Liv Morgan", "Lola Vice", "Lyra Valkyria", "Maryse", "Maxxine Dupri",
  "Michelle McCool", "Michin", "Molly Holly", "Naomi", "Natalya", "Nia Jax",
  "Nikki Bella", "Nikki Cross", "Nikkita Lyons", "Piper Niven", "Raquel Rodriguez",
  "Rhea Ripley", "Roxanne Perez", "Sensational Sherri", "Sol Ruca", "Stacy Keibler",
  "Stephanie McMahon", "Stephanie Vaquer", "Tatum Paxley", "Thea Hail",
  "Tiffany Stratton", "Trish Stratus", "Victoria", "Wendy Choo", "Wren Sinclair",
  "Zaria", "Zelina Vega", "Zoey Stark",
]);

export function inferGender(name: string): "M" | "F" {
  return WOMEN_NAMES.has(name) ? "F" : "M";
}

